spring:
  application:
    name: zh-ai-agent
  profiles:
    active: local
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1024 #向量嵌入模型embedding的度，不设置会根据实际的向量数去指定维度的数量，最好确定一下
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  main:
    allow-bean-definition-overriding: true



server:
  port: 8123
  servlet:
    context-path: /api #????????????????????????????????????/api??
# springdoc-openapi??????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zyf.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug